/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.Cadastro;

/**
 *
 * @author Usuario
 */
public class TelaCadastroDespesas extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroDespesas
     */
    public TelaCadastroDespesas() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameInputDespesas = new javax.swing.JTextField();
        valorInputDespesas = new javax.swing.JTextField();
        TipoListBox = new javax.swing.JComboBox<>();
        cadastroDespesasButton = new javax.swing.JButton();
        limparDespesasButton = new javax.swing.JButton();
        sairDespesasButton = new javax.swing.JButton();
        dataInputDespesas = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Data:");

        jLabel4.setText("Valor:");

        valorInputDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorInputDespesasActionPerformed(evt);
            }
        });

        TipoListBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cadastroDespesasButton.setText("Cadastrar");
        cadastroDespesasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroDespesasButtonActionPerformed(evt);
            }
        });

        limparDespesasButton.setText("Limpar");
        limparDespesasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDespesasButtonActionPerformed(evt);
            }
        });

        sairDespesasButton.setText("Sair");
        sairDespesasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairDespesasButtonActionPerformed(evt);
            }
        });

        dataInputDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataInputDespesasActionPerformed(evt);
            }
        });
        dataInputDespesas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dataInputDespesasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameInputDespesas)
                            .addComponent(valorInputDespesas)
                            .addComponent(TipoListBox, 0, 192, Short.MAX_VALUE)
                            .addComponent(dataInputDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastroDespesasButton)
                        .addGap(34, 34, 34)
                        .addComponent(limparDespesasButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(sairDespesasButton)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameInputDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TipoListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataInputDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorInputDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroDespesasButton)
                    .addComponent(limparDespesasButton)
                    .addComponent(sairDespesasButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairDespesasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairDespesasButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairDespesasButtonActionPerformed

    private void cadastroDespesasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroDespesasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroDespesasButtonActionPerformed

    private void limparDespesasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDespesasButtonActionPerformed
        //this.
    }//GEN-LAST:event_limparDespesasButtonActionPerformed

    private void valorInputDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorInputDespesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorInputDespesasActionPerformed

    private void dataInputDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataInputDespesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataInputDespesasActionPerformed

    private void dataInputDespesasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataInputDespesasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataInputDespesasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCadastroDespesas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TipoListBox;
    private javax.swing.JButton cadastroDespesasButton;
    private javax.swing.JFormattedTextField dataInputDespesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton limparDespesasButton;
    private javax.swing.JTextField nameInputDespesas;
    private javax.swing.JButton sairDespesasButton;
    private javax.swing.JTextField valorInputDespesas;
    // End of variables declaration//GEN-END:variables
}
