package visao;
import visao.Cadastro.TelaCadastroDespesas;
import visao.Cadastro.TelaCadastroReceita;
import visao.Cadastro.TelaCadastroCategoria;
import visao.Editar.TelaEditarDespesas;
import visao.Editar.TelaEditarReceita;
import visao.Editar.TelaEditarUsuario;
import visao.Editar.TelaEditarCategoria;


public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadastroUsuario = new javax.swing.JMenuItem();
        jMenuCadastroDespesas = new javax.swing.JMenuItem();
        jMenuCadastroReceita = new javax.swing.JMenuItem();
        jMenuCadastroCategoria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuEditarDespesas = new javax.swing.JMenuItem();
        jMenuEditarReceita = new javax.swing.JMenuItem();
        jMenuEditarCategoria = new javax.swing.JMenuItem();
        PerfilMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuEditarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        jMenuCadastroUsuario.setText("Usuario");
        jMenuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroUsuario);

        jMenuCadastroDespesas.setText("Despesa");
        jMenuCadastroDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroDespesasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroDespesas);

        jMenuCadastroReceita.setText("Receita");
        jMenuCadastroReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroReceitaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroReceita);

        jMenuCadastroCategoria.setText("Categoria");
        jMenuCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroCategoria);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Editar");

        jMenuEditarDespesas.setText("Despesas");
        jMenuEditarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarDespesasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEditarDespesas);

        jMenuEditarReceita.setText("Receita");
        jMenuEditarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarReceitaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEditarReceita);

        jMenuEditarCategoria.setText("Categoria");
        jMenuEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEditarCategoria);

        jMenuBar1.add(jMenu3);

        PerfilMenu.setText("Perfil");

        jMenuItem6.setText("Visualizar");
        PerfilMenu.add(jMenuItem6);

        jMenuEditarUsuario.setText("Editar");
        jMenuEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarUsuarioActionPerformed(evt);
            }
        });
        PerfilMenu.add(jMenuEditarUsuario);

        jMenuBar1.add(PerfilMenu);

        jMenu2.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuCadastroDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroDespesasActionPerformed
        new TelaCadastroDespesas().setVisible(true);
    }//GEN-LAST:event_jMenuCadastroDespesasActionPerformed

    private void jMenuCadastroReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroReceitaActionPerformed
        new TelaCadastroReceita().setVisible(true);
    }//GEN-LAST:event_jMenuCadastroReceitaActionPerformed

    private void jMenuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroUsuarioActionPerformed
        new TelaCadastroUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuCadastroUsuarioActionPerformed

    private void jMenuEditarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarReceitaActionPerformed
       new TelaEditarReceita().setVisible(true);
    }//GEN-LAST:event_jMenuEditarReceitaActionPerformed

    private void jMenuEditarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarDespesasActionPerformed
        new TelaEditarDespesas().setVisible(true);
    }//GEN-LAST:event_jMenuEditarDespesasActionPerformed

    private void jMenuEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarCategoriaActionPerformed
        new TelaEditarCategoria().setVisible(true);
    }//GEN-LAST:event_jMenuEditarCategoriaActionPerformed

    private void jMenuEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarUsuarioActionPerformed
        new TelaEditarUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuEditarUsuarioActionPerformed

    private void jMenuCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroCategoriaActionPerformed
        new TelaCadastroCategoria().setVisible(true);
    }//GEN-LAST:event_jMenuCadastroCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu PerfilMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastroCategoria;
    private javax.swing.JMenuItem jMenuCadastroDespesas;
    private javax.swing.JMenuItem jMenuCadastroReceita;
    private javax.swing.JMenuItem jMenuCadastroUsuario;
    private javax.swing.JMenuItem jMenuEditarCategoria;
    private javax.swing.JMenuItem jMenuEditarDespesas;
    private javax.swing.JMenuItem jMenuEditarReceita;
    private javax.swing.JMenuItem jMenuEditarUsuario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
